# Generated by Django 5.2.6 on 2025-10-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_Categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_Categoria',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
